<a href="https://colab.research.google.com/github/sukjin1/ed/blob/main/backpropagation_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

이 코드에서는 시그모이드 활성화 함수를 사용하며, 입력과 목표 출력을 정의합니다. 그런 다음 backpropagation() 함수를 사용하여 역전파 알고리즘을 수행합니다. 학습률과 학습 반복 횟수를 설정하고, 학습이 완료된 후 새로운 입력에 대한 예측을 출력합니다.

이 예제는 XOR 문제를 해결하기 위해 2개의 입력과 1개의 출력을 갖는 인공 신경망을 구현합니다.

In [ ]:
import numpy as np

# 활성화 함수: 시그모이드 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 역전파 알고리즘
def backpropagation(inputs, targets, learning_rate, num_iterations):
    # 입력, 은닉층과 출력층의 크기
    input_size = inputs.shape[1]
    hidden_size = 4
    output_size = targets.shape[1]

    # 가중치 초기화
    weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
    weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))

    # 학습 반복
    for _ in range(num_iterations):
        # 순전파
        hidden_inputs = np.dot(inputs, weights_input_hidden)
        hidden_outputs = sigmoid(hidden_inputs)

        final_inputs = np.dot(hidden_outputs, weights_hidden_output)
        final_outputs = sigmoid(final_inputs)

        # 오차 계산
        output_errors = targets - final_outputs
        hidden_errors = np.dot(output_errors, weights_hidden_output.T)

        # 가중치 업데이트
        weights_hidden_output += learning_rate * np.dot(hidden_outputs.T, output_errors * final_outputs * (1 - final_outputs))
 #       weights_hidden_output += learning_rate * np.dot(hidden_outputs.T, output_errors)
        weights_input_hidden += learning_rate * np.dot(inputs.T, hidden_errors * hidden_outputs * (1 - hidden_outputs))

    return weights_input_hidden, weights_hidden_output

# 입력 데이터
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 목표 출력
targets = np.array([[0], [1], [1], [0]])

# 학습률과 학습 반복 횟수 설정
learning_rate = 0.1
num_iterations = 10000

# 역전파 알고리즘 수행
weights_input_hidden, weights_hidden_output = backpropagation(inputs, targets, learning_rate, num_iterations)

# 새로운 입력에 대한 예측
new_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
hidden_inputs = np.dot(new_inputs, weights_input_hidden)
hidden_outputs = sigmoid(hidden_inputs)
final_inputs = np.dot(hidden_outputs, weights_hidden_output)
final_outputs = sigmoid(final_inputs)

print("Predictions:")
print(final_outputs)


Predictions:
[[0.00475949]
 [0.99479202]
 [0.99506652]
 [0.0049117 ]]


In [ ]:
weights_input_hidden

array([[ 7.86310471,  5.90023917, -3.79281272, -2.44851146],
       [-3.75977174,  5.89677649,  8.01379372, -2.65674962]])

In [ ]:
weights_hidden_output

array([[-11.52643651],
       [ 17.53492029],
       [-11.64494207],
       [ -5.0492297 ]])