<a href="https://colab.research.google.com/github/sukjin1/ed/blob/main/%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

# 입력 데이터
X = np.array([[1], [2], [3], [4], [5]])
# 출력 데이터
y = np.array([2, 4, 6, 8, 10])

# 선형 회귀 모델 생성
model = LinearRegression()

# 모델 학습
model.fit(X, y)

# 테스트 데이터
X_test = np.array([[6], [7], [8], [9], [10]])

# 예측 결과
y_pred = model.predict(X_test)

# 회귀 계수와 절편
coef = model.coef_
intercept = model.intercept_

# 결과 출력
print("회귀 계수:", coef)
print("절편:", intercept)
print("예측 결과:", y_pred)

회귀 계수: [2.]
절편: 0.0
예측 결과: [12. 14. 16. 18. 20.]


아래 코드는 1부터 5까지의 x와 y 데이터를 생성하고, 이를 이용하여 선형 회귀 모델을 생성하고 훈련합니다. 그 다음, 훈련된 모델을 이용하여 새로운 x 값에 대한 y 값을 예측합니다. 마지막으로, 회귀식과 예측값을 출력합니다.

LinearRegression 클래스는 scikit-learn의 linear_model 모듈에서 제공되며, fit 메소드를 사용하여 모델을 훈련하고, predict 메소드를 사용하여 새로운 데이터에 대한 예측을 수행합니다.

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

# 독립 변수 x와 종속 변수 y를 정의
x = np.array([1, 2, 3, 4, 5]).reshape((-1, 1))
y = np.array([2, 3, 4, 5, 6])

# 선형 회귀 모델 생성
model = LinearRegression()

# 모델 훈련
model.fit(x, y)

# 회귀식 출력
print("회귀식: y = {:.2f}x + {:.2f}".format(model.coef_[0], model.intercept_))

# 예측
x_new = np.array([6]).reshape((-1, 1))
y_new = model.predict(x_new)
print("x가 6일 때 y 예측값: {:.2f}".format(y_new[0]))


회귀식: y = 1.00x + 1.00
x가 6일 때 y 예측값: 7.00


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reshaped_arr = arr.reshape(-1, 1)

print(arr)
# 출력: [1 2 3 4 5]

print(reshaped_arr)
# 출력: 
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]]

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]


위 코드에서 arr은 1차원 배열입니다. reshape(-1, 1)을 사용하여 arr을 2차원으로 재구성하면, reshaped_arr은 5행 1열의 2차원 배열로 변환됩니다. 이렇게 하면 각 원소가 하나의 열에 위치하게 됩니다.

reshape(-1, 1)을 사용하여 배열의 차원을 조정할 때, -1 자리에는 다른 값을 사용할 수도 있습니다. 다만, -1을 사용할 경우 해당 차원의 크기가 자동으로 계산되기 때문에, 다른 차원의 크기와 호환되어야 합니다.